version: '3.5'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3-alpine-3.18
    restart: always
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  application:
    container_name: gormsample
    build: .
    ports:
      - "5000:5000"

volumes:
  postgres-db:
    driver: local